"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const ACCESS_HASH = "53a262023ec1056f291cf2b332ffacbb2b790b9306ff9869e72c0d419d95e6eb";
const STORAGE_KEY = "pulsus-logica-clase-1-v1";

const translations = {
  es: {
    sections: ["Umbral", "Forma lógica", "Proposiciones", "Conectivas", "Verdad y validez", "Razonamiento", "Laboratorio", "Integración"], back: "Volver al Ágora", school: "Escuela de Metalkimia · Pulsus Fractum", saved: "Progreso guardado", completed: "Clase completada", degree: "Grado I · Lógica", subject: "Lógica I", visited: "tramos recorridos", eyebrow: "Fundamentos de Lógica I · Distinción y proposición", title: <>Lo ocurrido no es lo mismo<br/>que lo que decís que ocurrió.</>, quote: "Antes de reconfigurar una forma, necesitás poder leer su lógica.", previous: "Anterior", next: "Guardar y continuar", finish: "Completar la clase", reopen: "Reabrir la clase", gate: "Umbral de Lógica", gateTitle: <>La materia se abre<br/>con la palabra del campus.</>, gateBody: "Podés conocer el recorrido desde el Ágora. La clase, el laboratorio y tu bitácora pertenecen al espacio de cursantes.", password: "Palabra de acceso", open: "Abrir Lógica I", hint: "Usá la misma palabra que recibiste para Fundamentos.", error: "La Escuela todavía no reconoce esa palabra."
  },
  en: {
    sections: ["Threshold", "Logical form", "Propositions", "Connectives", "Truth and validity", "Reasoning", "Laboratory", "Integration"], back: "Back to the Agora", school: "School of Metalkimia · Pulsus Fractum", saved: "Progress saved", completed: "Class completed", degree: "Grade I · Logic", subject: "Logic I", visited: "sections visited", eyebrow: "Foundations of Logic I · Distinction and proposition", title: <>What happened is not the same<br/>as what you say happened.</>, quote: "Before reconfiguring a form, you need to read its logic.", previous: "Previous", next: "Save and continue", finish: "Complete class", reopen: "Reopen class", gate: "Threshold of Logic", gateTitle: <>The subject opens<br/>with the campus word.</>, gateBody: "You can discover the pathway from the Agora. The class, laboratory and journal belong to enrolled students.", password: "Access word", open: "Open Logic I", hint: "Use the same word you received for Foundations.", error: "The School does not recognize that word yet."
  }
};

type Lang = keyof typeof translations;
type SavedState = { active:number; visited:number[]; phrase:string; observed:string; conclusion:string; relation:string; alternative:string; note:string; completed:boolean };
const initial:SavedState = { active:0, visited:[0], phrase:"", observed:"", conclusion:"", relation:"", alternative:"", note:"", completed:false };

export default function LogicaClaseUnoPage() {
  const [lang,setLang] = useState<Lang>("es");
  const [checked,setChecked] = useState(false);
  const [access,setAccess] = useState(false);
  const [code,setCode] = useState("");
  const [error,setError] = useState("");
  const [state,setState] = useState<SavedState>(initial);
  const t = translations[lang];

  useEffect(() => {
    setAccess(window.sessionStorage.getItem("pulsus-campus-access") === "open");
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved) try { setState({...initial,...JSON.parse(saved)}); } catch { /* inicia una cursada limpia */ }
    setChecked(true);
  },[]);

  const update = (changes:Partial<SavedState>) => setState(current => { const next={...current,...changes}; window.localStorage.setItem(STORAGE_KEY,JSON.stringify(next)); return next; });
  const goTo = (active:number) => update({active,visited:Array.from(new Set([...state.visited,active])).sort((a,b)=>a-b)});
  const unlock = async (event:React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(code.trim().toUpperCase()));
    const hash=Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,"0")).join("");
    if(hash===ACCESS_HASH){window.sessionStorage.setItem("pulsus-campus-access","open");setAccess(true);setError("");}else setError(t.error);
  };
  const Language = () => <div className="pf-language"><button className={lang==="es"?"is-active":""} onClick={()=>setLang("es")}>ES</button><span>/</span><button className={lang==="en"?"is-active":""} onClick={()=>setLang("en")}>EN</button></div>;

  if(!checked) return <main className="school-access-gate"/>;
  if(!access) return <main className="school-access-gate"><div className="school-visitor-stars"/><Link className="school-access-back" href="/mpa/transmuta/pulsus-fractum?entry=mpa">← {t.back}</Link><Language/><section><div className="school-access-seal"><i>∴</i></div><p>{t.gate}</p><h1>{t.gateTitle}</h1><span>{t.gateBody}</span><form onSubmit={unlock}><label>{t.password}</label><div><input type="password" value={code} onChange={e=>{setCode(e.target.value);setError("");}} autoFocus/><button>{t.open} →</button></div><small className={error?"is-error":""}>{error||t.hint}</small></form></section></main>;

  const es=lang==="es";
  return <main className="pf-classroom pf-logic-classroom"><div className="pf-classroom-stars"/><header className="pf-classroom-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← {t.back}</Link><span>{t.school}</span><div><b>{state.completed?t.completed:t.saved}</b><Language/></div></header><div className="pf-classroom-layout"><aside className="pf-classroom-index"><p>{t.degree}</p><h2>{t.subject}</h2><div className="pf-classroom-progress"><i style={{width:`${state.completed?100:Math.max(16,((state.active+1)/t.sections.length)*100)}%`}}/></div><small>{state.completed?"100%":`${state.visited.length} / ${t.sections.length} ${t.visited}`}</small><nav>{t.sections.map((section,index)=><button key={section} className={state.active===index?"is-active":""} onClick={()=>goTo(index)}><em>{String(index+1).padStart(2,"0")}</em><span>{section}</span>{state.completed||state.visited.includes(index)?<b>✓</b>:null}</button>)}</nav><div className="pf-degree-mini"><p>Grado I</p><div><b>F1</b><i/><b className="is-open">L1</b><i/><b>A1</b><i/><b>F2</b><i/><b>L2</b><i/><b>A2</b><i/><b>F3</b><i/><b>L3</b><i/><b>A3</b></div><small>{es?"Segunda pieza del recorrido troncal":"Second piece of the common path"}</small></div><div className="pf-classroom-resource"><span>{es?"Material de cursada":"Course material"}</span><b>{es?"Cuaderno de Lógica I · versión imprimible":"Logic I workbook · printable edition"}</b><em>{es?"En preparación":"In preparation"}</em></div></aside><section className="pf-classroom-content"><div className="pf-classroom-eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><blockquote>“{t.quote}”</blockquote><div className="pf-classroom-panel">

  {state.active===0&&(es?<article><p className="pf-lesson-label">Umbral</p><h2>Una frase puede esconder una arquitectura</h2><p>“No respondió mi mensaje, entonces no le importo.” Parece una sola afirmación. Pero contiene un dato, una conclusión y un puente que los une.</p><Equation leftLabel="Dato" left="No respondió" rightLabel="Conclusión" right="No le importo"/><Callout title="Pregunta inaugural">¿El puente entre p y q estaba en lo ocurrido o fue introducido por quien observaba?</Callout><p>La lógica no viene a decirte qué pensar. Permite ver <b>qué operación realizaste para llegar hasta allí</b>.</p></article>:<article><p className="pf-lesson-label">Threshold</p><h2>A sentence can hide an architecture</h2><p>“They did not answer my message, therefore they do not care about me.” It contains a datum, a conclusion and a bridge between them.</p><Equation leftLabel="Datum" left="No answer" rightLabel="Conclusion" right="They do not care"/><Callout title="Opening question">Was the bridge between p and q present in the event, or introduced by the observer?</Callout><p>Logic does not tell you what to think. It reveals <b>which operation brought you there</b>.</p></article>)}
  {state.active===1&&(es?<article><p className="pf-lesson-label">El objeto de la lógica</p><h2>El contenido cambia. La forma puede permanecer.</h2><p>“Si llueve, la calle se moja” y “si no responde, no le importo” hablan de mundos distintos, pero comparten una forma: <b>si p, entonces q</b>. La lógica estudia esa estructura y pregunta si la conclusión se sigue de aquello que la sostiene.</p><div className="pf-distinction-grid"><div><b>Contenido</b><span>De qué habla una afirmación.</span></div><div><b>Forma</b><span>Cómo están organizadas sus partes.</span></div><div><b>Validez</b><span>Si la conclusión se sigue de las premisas.</span></div></div><Callout title="Pregunta matriz">¿Qué estructura está operando debajo de lo que estoy diciendo?</Callout><p>Pulsus Fractum agrega una segunda observación: ¿de dónde salieron las premisas y qué relación fue introducida por el observador?</p></article>:<article><p className="pf-lesson-label">The object of logic</p><h2>Content changes. Form can remain.</h2><p>“If it rains, the street gets wet” and “if they do not answer, they do not care” concern different worlds but share the form <b>if p, then q</b>. Logic studies this structure.</p><div className="pf-distinction-grid"><div><b>Content</b><span>What a statement is about.</span></div><div><b>Form</b><span>How its parts are organized.</span></div><div><b>Validity</b><span>Whether the conclusion follows from the premises.</span></div></div><Callout title="Matrix question">What structure is operating beneath what I am saying?</Callout></article>)}
  {state.active===2&&(es?<article><p className="pf-lesson-label">Lógica proposicional</p><h2>Átomos y composiciones</h2><p>Una proposición afirma algo que puede ser verdadero o falso. “La puerta está abierta” es una proposición. “¿Está abierta?” es una pregunta; “abrila” es una orden.</p><div className="pf-symbol-cards"><div><b>p</b><small>Atómica</small><span>No contiene otra proposición como parte.</span></div><div><b>p ∧ q</b><small>Molecular</small><span>Reúne proposiciones mediante una conectiva.</span></div></div><p>“Llegó tarde <b>y</b> no avisó” contiene dos unidades: p = llegó tarde; q = no avisó. La conjunción las convierte en una nueva proposición: <b>p ∧ q</b>.</p><Callout title="Simbolizar no empobrece">Suspende por un momento el contenido para hacer visible la arquitectura de la afirmación.</Callout></article>:<article><p className="pf-lesson-label">Propositional logic</p><h2>Atoms and compositions</h2><p>A proposition asserts something that can be true or false. “The door is open” is a proposition. “Is it open?” is a question; “open it” is a command.</p><div className="pf-symbol-cards"><div><b>p</b><small>Atomic</small><span>It contains no other proposition as a part.</span></div><div><b>p ∧ q</b><small>Molecular</small><span>It joins propositions through a connective.</span></div></div><p>“They arrived late <b>and</b> did not call” contains two units joined as <b>p ∧ q</b>.</p><Callout title="Symbolizing does not impoverish">It temporarily suspends content to reveal the architecture of the statement.</Callout></article>)}
  {state.active===3&&(es?<article><p className="pf-lesson-label">Operadores de configuración</p><h2>Cinco maneras de construir con proposiciones</h2><div className="pf-connective-list"><div><b>¬ p</b><span><strong>Negación</strong>No llegó.</span></div><div><b>p ∧ q</b><span><strong>Conjunción</strong>Llegó y llamó.</span></div><div><b>p ∨ q</b><span><strong>Disyunción</strong>Llegó o llamó.</span></div><div><b>p → q</b><span><strong>Condicional</strong>Si llegó, llamó.</span></div><div><b>p ↔ q</b><span><strong>Bicondicional</strong>Llegó si y sólo si llamó.</span></div></div><p>Cambiar una conectiva cambia la forma completa. “No vino <b>y</b> no avisó” no afirma lo mismo que “no vino <b>o</b> no avisó”.</p><Callout title="Lectura Pulsus">Cada conectiva admite y excluye posibilidades. Por eso también opera como una pequeña arquitectura de configuración.</Callout></article>:<article><p className="pf-lesson-label">Configuration operators</p><h2>Five ways of building with propositions</h2><div className="pf-connective-list"><div><b>¬ p</b><span><strong>Negation</strong>They did not arrive.</span></div><div><b>p ∧ q</b><span><strong>Conjunction</strong>They arrived and called.</span></div><div><b>p ∨ q</b><span><strong>Disjunction</strong>They arrived or called.</span></div><div><b>p → q</b><span><strong>Conditional</strong>If they arrived, they called.</span></div><div><b>p ↔ q</b><span><strong>Biconditional</strong>They arrived iff they called.</span></div></div><p>Changing a connective changes the entire form.</p><Callout title="Pulsus reading">Each connective admits and excludes possibilities. It therefore operates as a small configuration architecture.</Callout></article>)}
  {state.active===4&&(es?<article><p className="pf-lesson-label">Una distinción fundamental</p><h2>Verdad no es validez</h2><div className="pf-truth-comparison"><div><small>Proposición</small><b>Verdadera o falsa</b><p>Pregunta por su relación con aquello que afirma.</p></div><div><small>Razonamiento</small><b>Válido o inválido</b><p>Pregunta si la conclusión se sigue de las premisas.</p></div></div><p>Un razonamiento puede ser válido y partir de premisas falsas. También puede alcanzar por casualidad una conclusión verdadera mediante una inferencia inválida.</p><Callout title="Ejemplo">Todos los peces vuelan. DIMA es un pez. Por lo tanto, DIMA vuela. La forma es válida; sus premisas no son verdaderas.</Callout><p>Llegar a una conclusión correcta no demuestra que hayamos razonado correctamente.</p></article>:<article><p className="pf-lesson-label">A fundamental distinction</p><h2>Truth is not validity</h2><div className="pf-truth-comparison"><div><small>Proposition</small><b>True or false</b><p>It asks about what the proposition asserts.</p></div><div><small>Reasoning</small><b>Valid or invalid</b><p>It asks whether the conclusion follows from the premises.</p></div></div><p>Valid reasoning may begin with false premises. Invalid reasoning may accidentally reach a true conclusion.</p><Callout title="Example">All fish fly. DIMA is a fish. Therefore, DIMA flies. The form is valid; its premises are not true.</Callout></article>)}
  {state.active===5&&(es?<article><p className="pf-lesson-label">Premisas e inferencia</p><h2>¿Qué sostiene la conclusión?</h2><p>Un razonamiento no es una lista de frases. Algunas proposiciones funcionan como <b>premisas</b>: ofrecen razones. Otra funciona como <b>conclusión</b>: aquello que se afirma a partir de ellas. La <b>inferencia</b> es el pasaje.</p><div className="pf-reasoning-map"><span><small>Premisa 1</small>p</span><span><small>Premisa 2</small>p → q</span><i>∴</i><span><small>Conclusión</small>q</span></div><p>En el lenguaje cotidiano, “porque”, “puesto que” y “dado que” suelen anunciar premisas; “por lo tanto”, “entonces” y “en consecuencia” suelen anunciar conclusiones. A veces ninguna marca aparece.</p><Callout title="La pregunta lógica">Si aceptáramos las premisas, ¿estaríamos obligados a aceptar la conclusión?</Callout><Callout title="La pregunta Pulsus">¿Qué premisa quedó escondida para que la conclusión pareciera inevitable?</Callout></article>:<article><p className="pf-lesson-label">Premises and inference</p><h2>What supports the conclusion?</h2><p>Some propositions function as <b>premises</b>: they offer reasons. Another is the <b>conclusion</b>. The <b>inference</b> is the passage between them.</p><div className="pf-reasoning-map"><span><small>Premise 1</small>p</span><span><small>Premise 2</small>p → q</span><i>∴</i><span><small>Conclusion</small>q</span></div><Callout title="The logical question">If we accepted the premises, would we be required to accept the conclusion?</Callout><Callout title="The Pulsus question">Which hidden premise made the conclusion appear inevitable?</Callout></article>)}
  {state.active===6&&<article><p className="pf-lesson-label">{es?"Laboratorio I · Fractura":"Laboratory I · Fracture"}</p><h2>{es?"Capturá una inferencia cotidiana":"Capture an everyday inference"}</h2><p>{es?"No la mejores. Conservá la frase como apareció y después separá sus piezas.":"Do not improve it. Keep the sentence as it appeared, then separate its pieces."}</p><div className="pf-lab-fields"><Field label={es?"La frase completa":"The full sentence"} value={state.phrase} change={phrase=>update({phrase})}/><Field label={es?"p · Lo que observé":"p · What I observed"} value={state.observed} change={observed=>update({observed})}/><Field label={es?"q · Lo que concluí":"q · What I concluded"} value={state.conclusion} change={conclusion=>update({conclusion})}/><Field label={es?"La premisa o el puente escondido":"The hidden premise or bridge"} value={state.relation} change={relation=>update({relation})}/><Field wide label={es?"Caso que vuelve a abrir la relación":"A case that reopens the relation"} value={state.alternative} change={alternative=>update({alternative})}/></div><Callout title={es?"La prueba":"The test"}>{es?"No reemplaza tu conclusión por una más amable. Descubre cuánto de la relación estaba efectivamente demostrado.":"It does not replace your conclusion with a kinder one. It reveals how much of the relation was demonstrated."}</Callout></article>}
  {state.active===7&&<article><p className="pf-lesson-label">{es?"Integración I":"Integration I"}</p><h2>{es?"Ahora podés ver la operación":"Now you can see the operation"}</h2><ol>{(es?["La lógica estudia la forma de los razonamientos, no solamente su contenido.","Una proposición atómica puede integrar una proposición molecular.","Las conectivas organizan distintas relaciones entre proposiciones.","Verdad y validez responden preguntas diferentes.","Una conclusión posible no es necesariamente una conclusión demostrada.","Fracturar un razonamiento permite encontrar sus premisas ocultas."]:["Logic studies the form of reasoning, not only its content.","An atomic proposition can become part of a molecular proposition.","Connectives organize different relations between propositions.","Truth and validity answer different questions.","A possible conclusion is not necessarily demonstrated.","Fracturing reasoning reveals hidden premises."]).map(item=><li key={item}>{item}</li>)}</ol><label>{es?"Mi fragmento de integración":"My integration fragment"}<textarea value={state.note} onChange={e=>update({note:e.target.value})} placeholder={es?"Hoy pude distinguir que…":"Today I was able to distinguish…"}/></label><div className="pf-correspondences"><p>{es?"Correspondencias":"Correspondences"}</p><div><span><b>{es?"Capacidad":"Capacity"}</b>{es?"Distinguir":"Distinguish"}</span><span><b>{es?"Operación":"Operation"}</b>{es?"Fracturar":"Fracture"}</span><span><b>{es?"Materia":"Matter"}</b>{es?"Proposición":"Proposition"}</span><span><b>{es?"Próxima apertura":"Next opening"}</b>{es?"Inferencia":"Inference"}</span></div></div><p className="pf-source-note">{es?"Fuente formal de la línea: Telma Barreiro de Nudler y Oscar Nudler, Elementos de lógica simbólica. La traducción experiencial corresponde a Pulsus Fractum.":"Formal source for this pathway: Telma Barreiro de Nudler and Oscar Nudler, Elements of Symbolic Logic. The experiential translation belongs to Pulsus Fractum."}</p></article>}
  </div><div className="pf-classroom-controls"><button disabled={state.active===0} onClick={()=>goTo(state.active-1)}>← {t.previous}</button>{state.active<t.sections.length-1?<button className="primary" onClick={()=>goTo(state.active+1)}>{t.next} →</button>:<button className="primary" onClick={()=>update({completed:!state.completed})}>{state.completed?t.reopen:`${t.finish} ✓`}</button>}</div></section></div></main>;
}

function Equation({leftLabel,left,rightLabel,right}:{leftLabel:string;left:string;rightLabel:string;right:string}){return <div className="pf-logic-equation"><span><small>{leftLabel}</small><b>p</b>{left}</span><i>→</i><span><small>{rightLabel}</small><b>q</b>{right}</span></div>}
function Callout({title,children}:{title:string;children:React.ReactNode}){return <div className="pf-lesson-callout"><b>{title}</b><span>{children}</span></div>}
function Field({label,value,change,wide=false}:{label:string;value:string;change:(value:string)=>void;wide?:boolean}){return <label className={wide?"wide":""}>{label}<textarea value={value} onChange={e=>change(e.target.value)}/></label>}
