"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";

type House = "custos" | "reconfigura" | "architectus";
type Scores = Record<House, number>;
type Answer = { text: string; score: Scores };
const score = (custos=0,reconfigura=0,architectus=0):Scores => ({custos,reconfigura,architectus});
const houses = {
  custos:{name:"Custos",image:"/simbolos-casas/custos-medallon-v2.png",pdf:"/guias/oraculo-pasajes-custos.pdf"},
  reconfigura:{name:"Reconfiguradores",image:"/simbolos-casas/reconfiguradores-medallon-v2.png",pdf:"/guias/oraculo-pasajes-reconfiguradores.pdf"},
  architectus:{name:"Architectus",image:"/simbolos-casas/architectus-medallon-v2.png",pdf:"/guias/oraculo-pasajes-architectus.pdf"}
};
const questions:{scene:string;prompt:string;answers:Answer[]}[]=[
  {scene:"La vista · Una mesa después del encuentro",prompt:"Algo quedó fuera de lugar. ¿Qué mirás primero?",answers:[{text:"Qué cambió y dónde está el límite.",score:score(3,0,1)},{text:"Qué podría mover para probar otra forma.",score:score(0,3,1)},{text:"Cómo se relaciona cada cosa con las demás.",score:score(1,0,3)}]},
  {scene:"El oído · Una conversación se repite",prompt:"La charla vuelve siempre al mismo punto. ¿Qué escuchás?",answers:[{text:"Lo que se dice y lo que queda en silencio.",score:score(3,0,1)},{text:"La frase que podría cambiar la conversación.",score:score(0,3,1)},{text:"El patrón que conecta las distintas voces.",score:score(1,1,3)}]},
  {scene:"La orientación · Un mapa incompleto",prompt:"No sabés si el camino continúa. ¿Qué hacés?",answers:[{text:"Marco lo que sé y hasta dónde puedo avanzar.",score:score(3)},{text:"Pruebo un paso y observo qué sucede.",score:score(0,3)},{text:"Busco las señales que conectan las partes del mapa.",score:score(1,0,3)}]},
  {scene:"La imaginación · Una idea nueva",prompt:"La idea entusiasma, pero todavía no tiene forma. ¿Qué aportás?",answers:[{text:"Una base firme para que pueda sostenerse.",score:score(3,0,1)},{text:"Una primera prueba para verla en acción.",score:score(0,3,1)},{text:"Un lugar y una función para cada elemento.",score:score(0,1,3)}]},
  {scene:"El movimiento · Una regla que ya no sirve",prompt:"La regla antes ayudaba y ahora limita. ¿Qué hacés?",answers:[{text:"Distingo qué todavía vale la pena cuidar.",score:score(3,1)},{text:"La interrumpo y pruebo una alternativa.",score:score(0,3)},{text:"Reordeno el conjunto para que funcione de otra manera.",score:score(0,1,3)}]},
  {scene:"La percepción · Un espacio desconocido",prompt:"Entrás por primera vez. ¿Qué notás antes?",answers:[{text:"Los bordes, los silencios y quién cuida el lugar.",score:score(3)},{text:"La energía, la tensión y dónde algo podría cambiar.",score:score(0,3)},{text:"La distribución y la relación entre las partes.",score:score(0,0,3)}]},
  {scene:"La decisión · Poco tiempo para elegir",prompt:"Todavía te falta información. ¿En qué te apoyás?",answers:[{text:"En lo que es importante proteger.",score:score(3)},{text:"En la opción que devuelve movimiento.",score:score(0,3)},{text:"En la opción que mejor conecta las partes.",score:score(1,0,3)}]},
  {scene:"El tacto · Algo creció demasiado",prompt:"Ya no entra en la forma que lo contenía. ¿Qué hacés?",answers:[{text:"Conservo lo esencial y suelto lo que sobra.",score:score(3,0,1)},{text:"Abro la forma para que aparezca algo nuevo.",score:score(0,3,1)},{text:"Construyo una forma más amplia para contenerlo.",score:score(0,1,3)}]},
  {scene:"La correspondencia · Tres respuestas distintas",prompt:"Las tres tienen algo de verdad. ¿Cómo seguís?",answers:[{text:"Distingo qué está viendo cada persona.",score:score(3,0,1)},{text:"Las pongo en diálogo para que aparezca otra posibilidad.",score:score(0,3,1)},{text:"Busco qué las conecta sin borrar sus diferencias.",score:score(1,1,3)}]}
];

export default function OraculoPage(){
  const [name,setName]=useState(""); const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [chosen,setChosen]=useState<Answer[]>([]);
  const result=useMemo(()=>{if(chosen.length!==questions.length)return null;const total=chosen.reduce((a,v)=>score(a.custos+v.score.custos,a.reconfigura+v.score.reconfigura,a.architectus+v.score.architectus),score());const first:House=total.custos>=total.reconfigura?"custos":"reconfigura";const expansion:House=first==="custos"?"reconfigura":"custos";return{first,expansion,architect:total.architectus>=12};},[chosen]);
  const reset=()=>{setStarted(false);setStep(0);setChosen([])};
  const choose=(answer:Answer)=>{setChosen([...chosen,answer]);if(step<questions.length-1)setStep(step+1)};
  const download=()=>{if(!result)return;const c=document.createElement("canvas");c.width=1200;c.height=1500;const x=c.getContext("2d");if(!x)return;const g=x.createLinearGradient(0,0,1200,1500);g.addColorStop(0,"#210b22");g.addColorStop(1,"#050207");x.fillStyle=g;x.fillRect(0,0,1200,1500);x.strokeStyle="#967B45";x.lineWidth=3;x.strokeRect(55,55,1090,1390);x.textAlign="center";x.fillStyle="#d45a9f";x.font="26px Arial";x.fillText("ORÁCULO DE LOS PASAJES",600,145);x.fillStyle="#c6a967";x.font="72px Georgia";x.fillText(`${name.trim()}, tus puertas`,600,255);x.fillStyle="#c9bbc5";x.font="italic 30px Georgia";x.fillText("respondieron en este orden",600,310);([result.first,result.expansion,"architectus"] as House[]).forEach((h,i)=>{const px=140+i*335,py=450,w=250,hh=470;x.beginPath();x.moveTo(px,py+hh);x.lineTo(px,py+150);x.quadraticCurveTo(px+w/2,py-70,px+w,py+150);x.lineTo(px+w,py+hh);x.closePath();x.fillStyle=i===0?"#562247":"#1d0b20";x.fill();x.strokeStyle="#967B45";x.lineWidth=i===0?6:3;x.stroke();x.fillStyle="#d45a9f";x.font="19px Arial";x.fillText(i===0?"PRIMER PASAJE":i===1?"EXPANSIÓN":"HORIZONTE",px+w/2,py+250);x.fillStyle="#c6a967";x.font="bold 28px Georgia";x.fillText(houses[h].name,px+w/2,py+310)});x.fillStyle="#c9bbc5";x.font="28px Georgia";x.fillText("El Oráculo orienta. La decisión siempre es tuya.",600,1060);x.fillStyle="#c6a967";x.font="italic 34px Georgia";x.fillText("Una vez que ves, ya no podés desver.",600,1140);x.fillStyle="#8e7888";x.font="20px Arial";x.fillText("ESCUELA DE METALKIMIA · PULSUS FRACTUM",600,1350);const a=document.createElement("a");a.download=`mis-pasajes-${name.trim().toLowerCase().replace(/\s+/g,"-")}.png`;a.href=c.toDataURL();a.click()};
  if(!started)return <main className="oracle-shell"><div className="oracle-stars"/><header className="oracle-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← Volver al Ágora</Link><span>Escuela de Metalkimia</span></header><section className="oracle-threshold"><p>Una ceremonia de orientación</p><h1>Oráculo de los Pasajes</h1><blockquote>Las puertas no eligen quién sos. Revelan desde dónde podés comenzar.</blockquote><div className="oracle-seals">{(["custos","architectus","reconfigura"] as House[]).map(h=><Image key={h} src={houses[h].image} alt="" width={724} height={724}/>)}</div><div className="oracle-intro"><p>Vas a atravesar nueve escenas simples. Cada una observa un sentido o una manera de responder.</p><p>No hay respuestas correctas. Elegí lo que más se parece a lo que hacés. Al final vas a descubrir con qué pasaje se corresponden tus elecciones.</p></div><label>¿Cómo querés que te nombre el Oráculo?<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" maxLength={40}/></label><button disabled={!name.trim()} onClick={()=>setStarted(true)}>Golpear la primera puerta →</button><small>Orientación simbólica y pedagógica · 4 minutos</small></section></main>;
  if(!result){const q=questions[step];return <main className="oracle-shell"><div className="oracle-stars"/><header className="oracle-header"><button onClick={reset}>← Salir</button><span>{String(step+1).padStart(2,"0")} / {questions.length}</span></header><section className="oracle-question"><div className="oracle-progress"><i style={{width:`${(step+1)/questions.length*100}%`}}/></div><p>{q.scene}</p><h1>{q.prompt}</h1><div>{q.answers.map((a,i)=><button key={a.text} onClick={()=>choose(a)}><span>{String.fromCharCode(65+i)}</span>{a.text}</button>)}</div><small>Respondé desde lo que hacés, aunque no sea lo que elegirías contar.</small></section></main>}
  const first=houses[result.first],expansion=houses[result.expansion];return <main className="oracle-shell oracle-result"><div className="oracle-stars"/><header className="oracle-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← Volver al Ágora</Link><span>Tus puertas han respondido</span></header><section className="oracle-revelation"><p>Lectura de pasaje</p><h1>{name.trim()}, este es el orden<br/>en que tus puertas responden.</h1><div className="oracle-doors"><Door house={result.first} label="La puerta que reconoce tu potencia" note="Tu primer pasaje" active/><Door house={result.expansion} label="La puerta que puede expandirte" note="Tu expansión"/><Door house="architectus" label="La puerta que podrías construir" note={result.architect?"Potencia reconocida":"Horizonte posible"} active={result.architect}/></div><p className="oracle-choice">El Oráculo orienta. La decisión siempre es tuya.</p></section><section className="oracle-reading"><div><p>La correspondencia de tus elecciones</p><h2>Tu primer pasaje es {first.name}.</h2><span>{result.first==="custos"?"Tus sentidos tienden a registrar primero los límites, los silencios y aquello que necesita cuidado.":"Tus sentidos tienden a registrar primero la tensión, el movimiento y la posibilidad de cambiar una forma."} No es una etiqueta: es una orientación para comenzar por una capacidad que ya está presente.</span></div><div className="oracle-reading-grid"><Card label="Lo que percibís" text={result.first==="custos"?"Notás bordes, condiciones y aquello que sostiene una situación.":"Notás tensiones, movimientos y lugares donde algo puede transformarse."}/><Card label="Cómo respondés" text={result.first==="custos"?"Observás y delimitás antes de actuar.":"Probás un movimiento para abrir otra posibilidad."}/><Card label="Tu cuidado" text={result.first==="custos"?"Que observar no se convierta en esperar para siempre.":"Que intervenir no se adelante a lo que todavía necesita ser visto."}/><Card label="Tu expansión" text={`${expansion.name} puede sumar otra manera de percibir y actuar sin borrar la tuya.`}/></div>{result.architect&&<blockquote>También apareció una potencia Architectus: buscás la correspondencia entre las partes y tendés a imaginar el conjunto. Architectus es una especialización; para llegar, primero necesitás atravesar Custos o Reconfiguradores.</blockquote>}<div className="oracle-actions"><button onClick={download}>Descargar la imagen de mis puertas ↓</button><a href={first.pdf} download>Descargar guía de {first.name} ↓</a><button onClick={reset}>Realizar otra lectura</button></div><footer><b>Una vez que ves, ya no podés desver.</b><span>Esta lectura no determina quién sos. Reconoce desde dónde estás entrando hoy.</span></footer></section></main>
}
function Door({house,label,note,active=false}:{house:House;label:string;note:string;active?:boolean}){return <article className={active?"is-first":""}><small>{label}</small><Image src={houses[house].image} alt={`Símbolo de ${houses[house].name}`} width={724} height={724}/><b>{houses[house].name}</b><span>{note}</span></article>}
function Card({label,text}:{label:string;text:string}){return <article><small>{label}</small><h3>{text}</h3></article>}
