"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";

type House = "custos" | "reconfigura" | "architectus";
type Scores = Record<House, number>;
type Answer = { text: string; score: Scores };
const score = (custos=0,reconfigura=0,architectus=0):Scores => ({custos,reconfigura,architectus});
const houses = {
  custos:{name:"Custos",image:"/simbolos-casas/custos-medallon-v2.png",pdf:"/guias/oraculo-pasajes-custos.pdf"},
  reconfigura:{name:"Reconfiguradores",image:"/simbolos-casas/reconfiguradores-medallon-v2.png",pdf:"/guias/oraculo-pasajes-reconfiguradores.pdf"},
  architectus:{name:"Architectus",image:"/simbolos-casas/architectus-medallon-v2.png",pdf:"/guias/oraculo-pasajes-architectus.pdf"}
};
const questions:{scene:string;prompt:string;answers:Answer[]}[]=[
  {scene:"Una mesa después del encuentro",prompt:"Todos se fueron. Algo quedó fuera de lugar. ¿Qué hacés primero?",answers:[{text:"Miro qué cambió y qué conviene preservar.",score:score(3,0,1)},{text:"Muevo una pieza y observo qué empieza a ordenarse.",score:score(0,3,1)},{text:"Reconstruyo cómo cada cosa llegó hasta ahí.",score:score(1,0,3)}]},
  {scene:"Una conversación se traba",prompt:"La misma discusión vuelve por tercera vez. ¿Qué aparece en vos?",answers:[{text:"Separo hechos, interpretaciones y responsabilidades.",score:score(3,0,1)},{text:"Busco una pregunta que cambie el movimiento.",score:score(0,3,1)},{text:"Veo el patrón que organiza a todos, aunque nadie lo nombre.",score:score(1,1,3)}]},
  {scene:"Te entregan un mapa incompleto",prompt:"Faltan referencias y nadie sabe si el camino continúa. ¿Qué te atrae?",answers:[{text:"Reconocer el borde seguro antes de avanzar.",score:score(3)},{text:"Probar una dirección y corregir con lo que ocurra.",score:score(0,3)},{text:"Entender la lógica con la que fue construido el mapa.",score:score(1,0,3)}]},
  {scene:"Alguien trae una idea brillante",prompt:"La idea entusiasma, pero todavía no tiene forma. ¿Qué aportás?",answers:[{text:"Las condiciones que necesita para no desarmarse.",score:score(3,0,1)},{text:"El primer experimento para volverla experiencia.",score:score(0,3,1)},{text:"Una estructura donde cada elemento cumpla una función.",score:score(0,1,3)}]},
  {scene:"Una regla ya no funciona",prompt:"Fue útil durante mucho tiempo, pero ahora limita. ¿Cuál es tu impulso?",answers:[{text:"Distinguir qué todavía protege y qué ya no corresponde.",score:score(3,1)},{text:"Interrumpirla y ensayar una regla nueva.",score:score(0,3)},{text:"Rediseñar el sistema para que deje de ser necesaria.",score:score(0,1,3)}]},
  {scene:"Entrás en un espacio desconocido",prompt:"Antes de que alguien explique nada, ¿qué capta tu atención?",answers:[{text:"Los límites, los silencios y quién sostiene el marco.",score:score(3)},{text:"La tensión, lo que circula y dónde podría cambiar.",score:score(0,3)},{text:"La distribución, las relaciones y el propósito del conjunto.",score:score(0,0,3)}]},
  {scene:"Una decisión no puede esperar",prompt:"La información es insuficiente. ¿Desde dónde elegís?",answers:[{text:"Desde aquello que no estoy dispuesta a comprometer.",score:score(3)},{text:"Desde el movimiento que devuelve capacidad de acción.",score:score(0,3)},{text:"Desde lo que conserva mayor coherencia entre las partes.",score:score(1,0,3)}]},
  {scene:"Algo valioso creció demasiado",prompt:"Ya no entra en la forma que lo contenía. ¿Qué hacés?",answers:[{text:"Cuido el núcleo y decido qué no debe perderse.",score:score(3,0,1)},{text:"Rompo la forma anterior para que aparezca otra.",score:score(0,3,1)},{text:"Construyo un continente capaz de alojar su nueva escala.",score:score(0,1,3)}]},
  {scene:"Tres voces ofrecen respuestas distintas",prompt:"Ninguna parece completamente equivocada. ¿Cómo seguís?",answers:[{text:"Preciso qué pregunta está respondiendo cada una.",score:score(3,0,1)},{text:"Las pongo en relación para ver qué producen juntas.",score:score(0,3,1)},{text:"Busco el nivel donde correspondan sin fusionarse.",score:score(1,1,3)}]}
];

export default function OraculoPage(){
  const [name,setName]=useState(""); const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [chosen,setChosen]=useState<Answer[]>([]);
  const result=useMemo(()=>{if(chosen.length!==questions.length)return null;const total=chosen.reduce((a,v)=>score(a.custos+v.score.custos,a.reconfigura+v.score.reconfigura,a.architectus+v.score.architectus),score());const first:House=total.custos>=total.reconfigura?"custos":"reconfigura";const expansion:House=first==="custos"?"reconfigura":"custos";return{first,expansion,architect:total.architectus>=12};},[chosen]);
  const reset=()=>{setStarted(false);setStep(0);setChosen([])};
  const choose=(answer:Answer)=>{setChosen([...chosen,answer]);if(step<questions.length-1)setStep(step+1)};
  const download=()=>{if(!result)return;const c=document.createElement("canvas");c.width=1200;c.height=1500;const x=c.getContext("2d");if(!x)return;const g=x.createLinearGradient(0,0,1200,1500);g.addColorStop(0,"#210b22");g.addColorStop(1,"#050207");x.fillStyle=g;x.fillRect(0,0,1200,1500);x.strokeStyle="#967B45";x.lineWidth=3;x.strokeRect(55,55,1090,1390);x.textAlign="center";x.fillStyle="#d45a9f";x.font="26px Arial";x.fillText("ORÁCULO DE LOS PASAJES",600,145);x.fillStyle="#c6a967";x.font="72px Georgia";x.fillText(`${name.trim()}, tus puertas`,600,255);x.fillStyle="#c9bbc5";x.font="italic 30px Georgia";x.fillText("respondieron en este orden",600,310);([result.first,result.expansion,"architectus"] as House[]).forEach((h,i)=>{const px=140+i*335,py=450,w=250,hh=470;x.beginPath();x.moveTo(px,py+hh);x.lineTo(px,py+150);x.quadraticCurveTo(px+w/2,py-70,px+w,py+150);x.lineTo(px+w,py+hh);x.closePath();x.fillStyle=i===0?"#562247":"#1d0b20";x.fill();x.strokeStyle="#967B45";x.lineWidth=i===0?6:3;x.stroke();x.fillStyle="#d45a9f";x.font="19px Arial";x.fillText(i===0?"PRIMER PASAJE":i===1?"EXPANSIÓN":"HORIZONTE",px+w/2,py+250);x.fillStyle="#c6a967";x.font="bold 28px Georgia";x.fillText(houses[h].name,px+w/2,py+310)});x.fillStyle="#c9bbc5";x.font="28px Georgia";x.fillText("El Oráculo orienta. La decisión siempre es tuya.",600,1060);x.fillStyle="#c6a967";x.font="italic 34px Georgia";x.fillText("Una vez que ves, ya no podés desver.",600,1140);x.fillStyle="#8e7888";x.font="20px Arial";x.fillText("ESCUELA DE METALKIMIA · PULSUS FRACTUM",600,1350);const a=document.createElement("a");a.download=`mis-pasajes-${name.trim().toLowerCase().replace(/\s+/g,"-")}.png`;a.href=c.toDataURL();a.click()};
  if(!started)return <main className="oracle-shell"><div className="oracle-stars"/><header className="oracle-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← Volver al Ágora</Link><span>Escuela de Metalkimia</span></header><section className="oracle-threshold"><p>Una ceremonia de orientación</p><h1>Oráculo de los Pasajes</h1><blockquote>Las puertas no eligen quién sos. Revelan desde dónde podés comenzar.</blockquote><div className="oracle-seals">{(["custos","architectus","reconfigura"] as House[]).map(h=><Image key={h} src={houses[h].image} alt="" width={724} height={724}/>)}</div><div className="oracle-intro"><p>Vas a atravesar nueve escenas. No hay respuestas correctas: elegí lo que más se parezca a lo que realmente hacés.</p><p>El Oráculo lee las huellas de tus elecciones y señala un recorrido posible. En MPA nadie decide por vos.</p></div><label>¿Cómo querés que te nombre el Oráculo?<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" maxLength={40}/></label><button disabled={!name.trim()} onClick={()=>setStarted(true)}>Golpear la primera puerta →</button><small>Orientación simbólica y pedagógica · 4 minutos</small></section></main>;
  if(!result){const q=questions[step];return <main className="oracle-shell"><div className="oracle-stars"/><header className="oracle-header"><button onClick={reset}>← Salir</button><span>{String(step+1).padStart(2,"0")} / {questions.length}</span></header><section className="oracle-question"><div className="oracle-progress"><i style={{width:`${(step+1)/questions.length*100}%`}}/></div><p>{q.scene}</p><h1>{q.prompt}</h1><div>{q.answers.map((a,i)=><button key={a.text} onClick={()=>choose(a)}><span>{String.fromCharCode(65+i)}</span>{a.text}</button>)}</div><small>Respondé desde lo que hacés, aunque no sea lo que elegirías contar.</small></section></main>}
  const first=houses[result.first],expansion=houses[result.expansion];return <main className="oracle-shell oracle-result"><div className="oracle-stars"/><header className="oracle-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← Volver al Ágora</Link><span>Tus puertas han respondido</span></header><section className="oracle-revelation"><p>Lectura de pasaje</p><h1>{name.trim()}, este es el orden<br/>en que tus puertas responden.</h1><div className="oracle-doors"><Door house={result.first} label="La puerta que reconoce tu potencia" note="Tu primer pasaje" active/><Door house={result.expansion} label="La puerta que puede expandirte" note="Tu expansión"/><Door house="architectus" label="La puerta que podrías construir" note={result.architect?"Potencia reconocida":"Horizonte posible"} active={result.architect}/></div><p className="oracle-choice">El Oráculo orienta. La decisión siempre es tuya.</p></section><section className="oracle-reading"><div><p>Tu configuración visible</p><h2>Primero reconocés desde {first.name}.</h2><span>En tus elecciones aparece una tendencia a {result.first==="custos"?"observar, delimitar y cuidar aquello que sostiene la forma":"intervenir, mover relaciones y abrir otra posibilidad"}. Este camino puede volver más precisa y fértil una capacidad que ya usás.</span></div><div className="oracle-reading-grid"><Card label="Cómo mirás" text={result.first==="custos"?"Leés bordes, condiciones y aquello que sostiene la forma.":"Leés tensiones, movimientos y posibilidades de transformación."}/><Card label="Tu potencia" text={result.first==="custos"?"Cuidar lo valioso sin confundir cuidado con inmovilidad.":"Abrir alternativas sin confundir movimiento con dirección."}/><Card label="Cuando se excede" text={result.first==="custos"?"La observación puede demorarse hasta convertirse en espera.":"La intervención puede adelantarse a lo que todavía necesitaba ser visto."}/><Card label="Lo que puede abrirse" text={`${expansion.name} puede ampliar tu repertorio sin borrar tu manera de entrar.`}/></div>{result.architect&&<blockquote>También apareció una potencia Architectus: tendés a buscar correspondencia entre las partes y a imaginar la configuración completa. Architectus es una especialización; para llegar, primero necesitás atravesar Custos o Reconfiguradores.</blockquote>}<div className="oracle-actions"><button onClick={download}>Descargar la imagen de mis puertas ↓</button><a href={first.pdf} download>Descargar guía de {first.name} ↓</a><button onClick={reset}>Realizar otra lectura</button></div><footer><b>Una vez que ves, ya no podés desver.</b><span>Esta lectura no determina quién sos. Reconoce desde dónde estás entrando hoy.</span></footer></section></main>
}
function Door({house,label,note,active=false}:{house:House;label:string;note:string;active?:boolean}){return <article className={active?"is-first":""}><small>{label}</small><Image src={houses[house].image} alt={`Símbolo de ${houses[house].name}`} width={724} height={724}/><b>{houses[house].name}</b><span>{note}</span></article>}
function Card({label,text}:{label:string;text:string}){return <article><small>{label}</small><h3>{text}</h3></article>}
