"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";

type House = "custos" | "reconfigura" | "architectus";
type Scores = Record<House, number>;
type Answer = { text: string; score: Scores };
const score = (custos=0,reconfigura=0,architectus=0):Scores => ({custos,reconfigura,architectus});
const houses = {
  custos:{name:"Custos",image:"/simbolos-casas/custos-medallon-v2.png",pdf:"/guias/oraculo-pasajes-custos.pdf"},
  reconfigura:{name:"Reconfiguradores",image:"/simbolos-casas/reconfiguradores-medallon-v2.png",pdf:"/guias/oraculo-pasajes-reconfiguradores.pdf"},
  architectus:{name:"Architectus",image:"/simbolos-casas/architectus-medallon-v2.png",pdf:"/guias/oraculo-pasajes-architectus.pdf"}
};
const questions:{scene:string;context:string;prompt:string;whisper?:{house:House;text:string};answers:Answer[]}[]=[
  {scene:"I · El vestíbulo",context:"La gran puerta se cierra detrás de vos. En el vestíbulo todavía arden tres velas y, sobre una mesa, un objeto fue movido. Nadie te dice cuál. Solo tenés unos segundos antes de que la sala vuelva a oscurecerse.",prompt:"¿Dónde ponés tu atención?",answers:[{text:"Muevo otro objeto y miro qué reacción provoca.",score:score(0,3,1)},{text:"Observo cómo está organizada toda la mesa.",score:score(1,0,3)},{text:"Busco la marca que dejó el objeto desplazado.",score:score(3,0,1)},{text:"Protejo la luz mientras pruebo qué pieza falta.",score:score(2,2,0)}]},
  {scene:"II · La galería de las voces",context:"Tres voces viajan por un corredor sin mostrarte sus rostros. Cambian las palabras, pero siempre tropiezan en el mismo lugar. Cuando una calla, las otras dos vuelven a empezar.",prompt:"¿Qué escuchás detrás de la discusión?",answers:[{text:"La relación que une a las tres voces.",score:score(1,0,3)},{text:"La palabra que ninguna se anima a decir.",score:score(3,0,1)},{text:"El punto exacto donde podrían escucharse de otra manera.",score:score(1,2,2)},{text:"La pregunta que interrumpiría la repetición.",score:score(0,3,1)}]},
  {scene:"III · El archivo sin final",context:"Un mapa antiguo termina en un borde rasgado. Sus marcas coinciden con una puerta cercana, pero no sabés qué hay detrás. El aire que entra por la cerradura parece venir de muy lejos.",prompt:"¿Cómo decidís si cruzar?",whisper:{house:"custos",text:"No todo límite encierra. Algunos límites permiten ver."},answers:[{text:"Abro apenas la puerta y observo qué cambia.",score:score(0,3,1)},{text:"Marco con claridad hasta dónde llega lo que sé.",score:score(3,0,0)},{text:"Comparo las marcas del mapa con las señales de la puerta.",score:score(1,0,3)},{text:"Aseguro el regreso antes de explorar lo desconocido.",score:score(2,1,1)}]},
  {scene:"IV · La sala de las ideas",context:"En el centro de una sala vacía flota una esfera. Al acercarte, proyecta una obra que todavía no existe. La imagen cambia con cada uno de tus movimientos.",prompt:"¿Qué le ofrecés para que pueda existir?",answers:[{text:"Una primera prueba, aunque todavía sea imperfecta.",score:score(0,3,1)},{text:"Una base capaz de sostenerla cuando la luz desaparezca.",score:score(3,0,1)},{text:"Una estructura donde cada parte tenga una función.",score:score(0,1,3)},{text:"Un pequeño ensayo y un borde claro para contenerlo.",score:score(2,2,0)}]},
  {scene:"V · El puente detenido",context:"Un puente suspendido divide el Campus. El mecanismo fue creado para proteger a quienes cruzan, pero ahora no deja pasar a nadie. Del otro lado, alguien espera.",prompt:"¿Cuál es tu primer movimiento?",whisper:{house:"reconfigura",text:"A veces abrir un camino no exige fuerza, sino cambiar una relación."},answers:[{text:"Estudio qué parte de la regla todavía protege.",score:score(3,1,0)},{text:"Rediseño el mecanismo completo antes de tocarlo.",score:score(0,1,3)},{text:"Cambio una pieza y observo si el puente responde.",score:score(0,3,1)},{text:"Busco una manera de abrirlo sin perder su protección.",score:score(2,2,1)}]},
  {scene:"VI · La cámara a oscuras",context:"Entrás en una cámara sin ventanas. No podés ver, pero el suelo vibra, una corriente roza tu piel y algo respira detrás de una pared. Podés encender una única lámpara.",prompt:"¿Hacia dónde dirigís la luz?",answers:[{text:"Hacia el lugar donde la vibración podría cambiar.",score:score(0,3,1)},{text:"Hacia el centro, para entender cómo se ordena la habitación.",score:score(0,0,3)},{text:"Hacia los bordes y las posibles salidas.",score:score(3,0,0)},{text:"Hacia la pared, relacionando el sonido con la corriente de aire.",score:score(1,1,2)}]},
  {scene:"VII · La campana",context:"La campana del Campus suena una sola vez. Frente a vos se abren cuatro senderos y la niebla empieza a cubrirlos. No existe una elección perfecta ni tiempo para conocerlo todo.",prompt:"¿Qué señal guía tu paso?",answers:[{text:"El sendero que conecta mejor todas las señales.",score:score(1,0,3)},{text:"El que permite avanzar y corregir después.",score:score(0,3,0)},{text:"El que conserva aquello que no quiero perder.",score:score(3,0,0)},{text:"El que abre una posibilidad sin abandonar lo esencial.",score:score(2,2,1)}]},
  {scene:"VIII · El jardín desbordado",context:"Una planta extraordinaria quebró la maceta que la sostuvo desde su primera hoja. Sus raíces siguen vivas y buscan tierra en distintas direcciones. Si esperás demasiado, podrían secarse.",prompt:"¿Cómo acompañás su crecimiento?",answers:[{text:"Diseño un jardín donde raíces y ramas tengan espacio.",score:score(0,1,3)},{text:"Conservo las raíces sanas y retiro lo que ya murió.",score:score(3,0,1)},{text:"Libero las raíces para que encuentren otra dirección.",score:score(0,3,1)},{text:"Cuido el núcleo mientras preparo un espacio nuevo.",score:score(2,1,2)}]},
  {scene:"IX · El consejo de las tres puertas",context:"Llegás al recinto final. Los tres guardianes hablan a la vez: uno señala lo que debe cuidarse, otro lo que pide cambiar y el tercero el dibujo que forman juntos. Ninguno posee toda la respuesta.",prompt:"¿Cómo recibís sus palabras?",whisper:{house:"architectus",text:"El conjunto no borra las diferencias. Las necesita para poder existir."},answers:[{text:"Los pongo en diálogo hasta que aparezca otra posibilidad.",score:score(0,3,1)},{text:"Busco qué los conecta sin volverlos iguales.",score:score(1,1,3)},{text:"Distingo con precisión qué está viendo cada uno.",score:score(3,0,1)},{text:"Reconozco qué cuidar, qué mover y cómo reunirlo.",score:score(2,2,2)}]}
];

export default function OraculoPage(){
  const [name,setName]=useState(""); const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [chosen,setChosen]=useState<Answer[]>([]);
  const result=useMemo(()=>{if(chosen.length!==questions.length)return null;const total=chosen.reduce((a,v)=>score(a.custos+v.score.custos,a.reconfigura+v.score.reconfigura,a.architectus+v.score.architectus),score());const first:House=total.custos>=total.reconfigura?"custos":"reconfigura";const expansion:House=first==="custos"?"reconfigura":"custos";return{first,expansion,architect:total.architectus>=12};},[chosen]);
  const reset=()=>{setStarted(false);setStep(0);setChosen([])};
  const choose=(answer:Answer)=>{setChosen([...chosen,answer]);if(step<questions.length-1)setStep(step+1)};
  const download=()=>{if(!result)return;const c=document.createElement("canvas");c.width=1200;c.height=1500;const x=c.getContext("2d");if(!x)return;const g=x.createLinearGradient(0,0,1200,1500);g.addColorStop(0,"#210b22");g.addColorStop(1,"#050207");x.fillStyle=g;x.fillRect(0,0,1200,1500);x.strokeStyle="#967B45";x.lineWidth=3;x.strokeRect(55,55,1090,1390);x.textAlign="center";x.fillStyle="#d45a9f";x.font="26px Arial";x.fillText("ORÁCULO DE LOS PASAJES",600,145);x.fillStyle="#c6a967";x.font="72px Georgia";x.fillText(`${name.trim()}, tus puertas`,600,255);x.fillStyle="#c9bbc5";x.font="italic 30px Georgia";x.fillText("respondieron en este orden",600,310);([result.first,result.expansion,"architectus"] as House[]).forEach((h,i)=>{const px=140+i*335,py=450,w=250,hh=470;x.beginPath();x.moveTo(px,py+hh);x.lineTo(px,py+150);x.quadraticCurveTo(px+w/2,py-70,px+w,py+150);x.lineTo(px+w,py+hh);x.closePath();x.fillStyle=i===0?"#562247":"#1d0b20";x.fill();x.strokeStyle="#967B45";x.lineWidth=i===0?6:3;x.stroke();x.fillStyle="#d45a9f";x.font="19px Arial";x.fillText(i===0?"PRIMER PASAJE":i===1?"EXPANSIÓN":"HORIZONTE",px+w/2,py+250);x.fillStyle="#c6a967";x.font="bold 28px Georgia";x.fillText(houses[h].name,px+w/2,py+310)});x.fillStyle="#c9bbc5";x.font="28px Georgia";x.fillText("El Oráculo orienta. La decisión siempre es tuya.",600,1060);x.fillStyle="#c6a967";x.font="italic 34px Georgia";x.fillText("Una vez que ves, ya no podés desver.",600,1140);x.fillStyle="#8e7888";x.font="20px Arial";x.fillText("ESCUELA DE METALKIMIA · PULSUS FRACTUM",600,1350);const a=document.createElement("a");a.download=`mis-pasajes-${name.trim().toLowerCase().replace(/\s+/g,"-")}.png`;a.href=c.toDataURL();a.click()};
  if(!started)return <main className="oracle-shell"><div className="oracle-stars"/><header className="oracle-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← Volver al Ágora</Link><span>Escuela de Metalkimia</span></header><section className="oracle-threshold"><p>Una ceremonia de orientación</p><h1>Oráculo de los Pasajes</h1><blockquote>Las puertas no eligen quién sos. Revelan desde dónde podés comenzar.</blockquote><div className="oracle-seals">{(["custos","architectus","reconfigura"] as House[]).map(h=><Image key={h} src={houses[h].image} alt="" width={724} height={724}/>)}</div><div className="oracle-intro"><p>Vas a atravesar nueve escenas cotidianas. Algunas preguntan qué mirás, qué escuchás o qué notás. Otras, qué solés hacer.</p><p>No hay respuestas correctas. Elegí la opción que más se parezca a vos. Al final vas a ver qué puerta se relaciona más con tus elecciones.</p></div><label>¿Cómo querés que te nombre el Oráculo?<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" maxLength={40}/></label><button disabled={!name.trim()} onClick={()=>setStarted(true)}>Golpear la primera puerta →</button><small>Orientación simbólica y pedagógica · 4 minutos</small></section></main>;
  if(!result){const q=questions[step];return <main className="oracle-shell"><div className="oracle-stars"/><header className="oracle-header"><button onClick={reset}>← Salir</button><span>{String(step+1).padStart(2,"0")} / {questions.length}</span></header><section className="oracle-question"><div className="oracle-progress"><i style={{width:`${(step+1)/questions.length*100}%`}}/></div><p>{q.scene}</p><blockquote className="oracle-scene">{q.context}</blockquote>{q.whisper&&<aside className="oracle-whisper"><Image src={houses[q.whisper.house].image} alt={`Símbolo de ${houses[q.whisper.house].name}`} width={724} height={724}/><span><b>{houses[q.whisper.house].name} susurra</b>{q.whisper.text}</span></aside>}<h1>{q.prompt}</h1><div>{q.answers.map((a,i)=><button key={a.text} onClick={()=>choose(a)}><span>{String.fromCharCode(65+i)}</span>{a.text}</button>)}</div><small>Elegí tu primer impulso. El Oráculo leerá la relación entre todas tus decisiones.</small></section></main>}
  const first=houses[result.first],expansion=houses[result.expansion];return <main className="oracle-shell oracle-result"><div className="oracle-stars"/><header className="oracle-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← Volver al Ágora</Link><span>Tus puertas han respondido</span></header><section className="oracle-revelation"><p>Lectura de pasaje</p><h1>{name.trim()}, este es el orden<br/>en que tus puertas responden.</h1><div className="oracle-doors"><Door house={result.first} label="La puerta que reconoce tu potencia" note="Tu primer pasaje" active/><Door house={result.expansion} label="La puerta que puede expandirte" note="Tu expansión"/><Door house="architectus" label="La puerta que podrías construir" note={result.architect?"Potencia reconocida":"Horizonte posible"} active={result.architect}/></div><p className="oracle-choice">El Oráculo orienta. La decisión siempre es tuya.</p></section><section className="oracle-reading"><div><p>Lo que tus elecciones tienen en común</p><h2>Tu primer pasaje es {first.name}.</h2><span>{result.first==="custos"?"Solés notar primero los límites, los silencios y aquello que necesita cuidado.":"Solés notar primero la tensión, el movimiento y los lugares donde algo podría cambiar."} En MPA llamamos correspondencia a esta relación entre lo que percibís, lo que hacés y la puerta que puede acompañarte. No es una etiqueta ni una decisión tomada por vos.</span></div><div className="oracle-reading-grid"><Card label="Lo que percibís" text={result.first==="custos"?"Notás los bordes, las condiciones y aquello que sostiene una situación.":"Notás tensiones, movimientos y lugares donde algo puede cambiar."}/><Card label="Cómo respondés" text={result.first==="custos"?"Observás y marcás los límites antes de actuar.":"Probás un movimiento para abrir otra posibilidad."}/><Card label="Lo que conviene cuidar" text={result.first==="custos"?"Que observar no se convierta en esperar para siempre.":"Que actuar no se adelante a lo que todavía necesita ser visto."}/><Card label="Otra puerta posible" text={`${expansion.name} puede sumar otra manera de percibir y actuar sin borrar la tuya.`}/></div><blockquote>{result.architect?"También apareció una posibilidad Architectus: tendés a buscar cómo se conectan las partes y a imaginar el conjunto.":"Architectus aparece como horizonte: en este recorrido pesó más tu manera inmediata de percibir y actuar que el impulso de organizar el conjunto."} En MPA, Architectus es una especialización. Para llegar, primero necesitás atravesar Custos o Reconfiguradores.</blockquote><div className="oracle-actions"><button onClick={download}>Descargar la imagen de mis puertas ↓</button><a href={first.pdf} download>Descargar guía de {first.name} ↓</a><button onClick={reset}>Realizar otra lectura</button></div><footer><b>Una vez que ves, ya no podés desver.</b><span>Esta lectura no determina quién sos. Reconoce desde dónde estás entrando hoy.</span></footer></section></main>
}
function Door({house,label,note,active=false}:{house:House;label:string;note:string;active?:boolean}){return <article className={active?"is-first":""}><small>{label}</small><Image src={houses[house].image} alt={`Símbolo de ${houses[house].name}`} width={724} height={724}/><b>{houses[house].name}</b><span>{note}</span></article>}
function Card({label,text}:{label:string;text:string}){return <article><small>{label}</small><h3>{text}</h3></article>}
