"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const COPY = {
  es: {
    back: "Volver al Ágora", school: "Escuela de Metalkimia · Pulsus Fractum", saved: "Progreso guardado", done: "Taller completado",
    gateOver: "Taller en vivo · 60 minutos", gateTitle: "La sala se abre con la palabra de esta convocatoria.", gateBody: "La experiencia pública puede recorrerse libremente. Este espacio contiene el encuentro guiado, el cuaderno y el certificado de participación.", key: "Palabra de acceso", open: "Entrar al taller →", bad: "La Escuela todavía no reconoce esa palabra.", hint: "Ingresá la clave recibida con tu inscripción.",
    degree: "Ágora libre · Taller con clave", title: "Principios universales", live: "Encuentro en vivo", pending: "El enlace de Zoom o Meet se habilita con la convocatoria", workbook: "Cuaderno del taller", workbookText: "Versión clara para imprimir, subrayar y completar", print: "Imprimir / guardar como PDF ↓",
    eyebrow: "Introducción a los principios universales", hero: "Su papel en la creación de tu realidad", sub: "Una perspectiva metalkímica de MPA", duration: "60 minutos", mode: "En vivo · Zoom / Meet", seven: "7 tramos guiados",
    previous: "← Anterior", next: "Guardar y continuar →", complete: "Completar el taller ✓", reopen: "Reabrir el taller", certificate: "Certificado de participación", name: "Nombre y apellido", attended: "Confirmo que participé del encuentro en vivo", issue: "Generar certificado →", lockedCert: "Completá los siete tramos y confirmá tu participación para habilitarlo.",
    sections: ["Preparación", "Umbral", "Siete lentes", "Hacer hablar", "Laboratorio", "El tercero", "Integración"],
  },
  en: {
    back: "Back to the Agora", school: "School of Metalkimia · Pulsus Fractum", saved: "Progress saved", done: "Workshop completed",
    gateOver: "Live workshop · 60 minutes", gateTitle: "The room opens with this session’s access word.", gateBody: "The public experience is open to everyone. This room contains the facilitated session, workbook and participation certificate.", key: "Access word", open: "Enter the workshop →", bad: "The School does not recognize that word yet.", hint: "Enter the key included with your registration.",
    degree: "Open Agora · Gated workshop", title: "Universal principles", live: "Live session", pending: "The Zoom or Meet link will be enabled with the invitation", workbook: "Workshop notebook", workbookText: "A clear version to print, underline and complete", print: "Print / save as PDF ↓",
    eyebrow: "Introduction to universal principles", hero: "Their role in creating your reality", sub: "An MPA metalkimical perspective", duration: "60 minutes", mode: "Live · Zoom / Meet", seven: "7 facilitated stages",
    previous: "← Previous", next: "Save and continue →", complete: "Complete workshop ✓", reopen: "Reopen workshop", certificate: "Certificate of participation", name: "Full name", attended: "I confirm that I attended the live session", issue: "Create certificate →", lockedCert: "Complete all seven stages and confirm your participation to enable it.",
    sections: ["Preparation", "Threshold", "Seven lenses", "Make it speak", "Laboratory", "The third", "Integration"],
  },
} as const;

const ACCESS_HASH = "8fbf4074954d6fb97748edc2f0e67cfbf0bf2615d48cbcc2dc112c14338f0302";
const STORAGE_KEY = "pulsus-principios-universales-v1";

const READINGS = {
  es: [
    { name: "Mentalismo", phrase: "Toda realidad vivida llega a través de una configuración mental.", text: "La tradición hermética afirma que «el Todo es mente». MPA no usa esta frase para decir que pensar algo alcanza para producirlo ni que una persona sea responsable de todo lo que le sucede. La usa como una invitación a reconocer la arquitectura desde la cual una experiencia se vuelve inteligible. Igual que un arquitecto imagina, selecciona y organiza antes de construir, la mente relaciona datos, recuerdos, expectativas y afectos. No inventa el terreno, pero participa en la forma que puede adquirir nuestra experiencia de ese terreno.", prompt: "¿Qué interpretación está organizando la situación que trajiste?" },
    { name: "Correspondencia", phrase: "Conocer una parte puede revelar relaciones del conjunto, si verificamos en ambas direcciones.", text: "«Como es arriba es abajo; como es adentro es afuera» aparece en los documentos como la imagen del espejo. Aquí la afinamos: correspondencia no significa que todo lo exterior sea una proyección tuya ni que debas culparte por lo que ocurre. Significa que una forma puede conservar relaciones reconocibles al cambiar de escala o de plano. Una habitación desordenada puede corresponderse con un momento de confusión, pero también puede no hacerlo. La operación es comparar, volver desde el afuera hacia el adentro y verificar si la relación se sostiene.", prompt: "¿Qué patrón aparece en más de una parte de tu situación? ¿Se sostiene al recorrerlo de vuelta?" },
    { name: "Vibración", phrase: "Nada permanece exactamente idéntico mientras está vivo.", text: "Los textos originales parten de «nada está inmóvil; todo se mueve». Podemos observarlo sin convertir movimiento en una escala moral de vibraciones altas y bajas. Un cuerpo aparentemente quieto respira; una relación estable modifica sus acuerdos; una idea repetida cambia de fuerza según el contexto. A veces sufrimos porque tratamos una forma pasajera como si debiera permanecer intacta. Percibir el movimiento no obliga a soltarlo todo: permite distinguir qué ya está cambiando, qué intentamos conservar y dónde todavía existe capacidad de intervención.", prompt: "¿Qué está cambiando aunque tu relato lo presente como fijo?" },
    { name: "Polaridad", phrase: "Dos opuestos pueden ser grados diferentes de una misma dimensión.", text: "Frío y calor no son sustancias enemigas: nombran posiciones en una escala térmica. La polaridad invita a buscar la dimensión común antes de quedar atrapados en una elección binaria. Esto no significa que todos los extremos sean equivalentes ni que haya que buscar siempre un punto medio. Significa comprobar si aquello que llamamos opuesto pertenece al mismo continuo y qué grados intermedios quedaron fuera de la mirada. La transformación comienza cuando aparece más de una posición posible.", prompt: "¿Qué dos polos estás tratando como las únicas alternativas? ¿Cuál es la dimensión que comparten?" },
    { name: "Ritmo", phrase: "Los movimientos dejan huellas, intervalos y recurrencias.", text: "El manuscrito usa la ola y el péndulo: ascenso, descenso, avance y repliegue. Su valor no está en prometer que cada caída será compensada de manera exacta, sino en enseñarnos a observar secuencias. Hay conversaciones, estados y proyectos que tienen tiempos distintos. Reconocer el ritmo evita confundir una fase con la totalidad y permite prepararse: guardar durante la expansión, descansar después del esfuerzo, intervenir antes de que una repetición se cierre otra vez sobre sí misma.", prompt: "¿Qué secuencia se repite? ¿En qué momento del ciclo estás hoy?" },
    { name: "Causa y efecto", phrase: "Toda acción participa en una red de consecuencias, pero rara vez actúa sola.", text: "Los materiales hablan de siembra y cosecha. Rescatamos la responsabilidad sin convertirla en culpa ni karma punitivo. Una consecuencia puede tener muchas causas, condiciones y participantes; y una acción puede producir efectos diferentes según el sistema en el que entra. La pregunta útil no es «¿qué hice para merecer esto?», sino «¿qué acciones, omisiones y condiciones producen o conservan esta configuración?». Allí donde reconocemos participación puede aparecer capacidad de respuesta.", prompt: "¿Qué sostiene hoy esta situación? Separá lo que depende de vos de lo que no." },
    { name: "Generación", phrase: "Cuando dos fuerzas se relacionan puede emerger un tercero que ninguna contenía sola.", text: "Los documentos de generación buscaban la integración de energías complementarias. MPA desplaza el foco de las identidades fijas hacia la función emergente. Una batería, un conductor y una lámpara no contienen por separado la luz encendida; la función aparece cuando la relación configura un circuito. Del mismo modo, dos personas no solo se afectan: pueden producir una conversación, una alianza, una rivalidad o una institución. Ese tercero también empieza a influir sobre quienes lo generaron.", prompt: "¿Qué sistema produce la relación que estás mirando? ¿Qué hace posible y qué conserva?" },
  ],
  en: [
    { name: "Mentalism", phrase: "Every lived reality reaches us through a mental configuration.", text: "Hermetic tradition states that ‘the All is mind’. MPA does not use this to claim that thinking something is enough to produce it, or that a person is responsible for everything that happens to them. It is an invitation to recognize the architecture through which an experience becomes intelligible. Like an architect who imagines, selects and organizes before building, the mind relates data, memories, expectations and affects. It does not invent the terrain, but it participates in the form our experience of that terrain can take.", prompt: "What interpretation is organizing the situation you brought?" },
    { name: "Correspondence", phrase: "A part may reveal relationships within the whole, if we verify them in both directions.", text: "‘As above, so below; as within, so without’ appears in the source documents as the image of a mirror. Here we make it more precise: correspondence does not mean that everything outside is your projection or that you should blame yourself for what happens. It means that a form may preserve recognizable relationships across scales or planes. A disordered room may correspond with a confused moment, but it may not. The operation is to compare, travel back from outside to inside, and verify whether the relationship holds.", prompt: "What pattern appears in more than one part of your situation? Does it hold on the way back?" },
    { name: "Vibration", phrase: "Nothing alive remains exactly identical.", text: "The original texts begin with ‘nothing rests; everything moves’. We can observe this without turning movement into a moral scale of high and low vibrations. A seemingly still body breathes; a stable relationship changes its agreements; a repeated idea changes force with context. We sometimes suffer because we treat a temporary form as if it had to remain intact. Perceiving movement does not require letting go of everything: it lets us distinguish what is already changing, what we try to preserve, and where intervention is still possible.", prompt: "What is changing even though your story presents it as fixed?" },
    { name: "Polarity", phrase: "Two opposites may be different degrees of the same dimension.", text: "Cold and heat are not enemy substances; they name positions on a thermal scale. Polarity invites us to find the shared dimension before becoming trapped in a binary choice. This does not mean that every extreme is equivalent or that the middle is always best. It means testing whether what we call opposites belongs to the same continuum and which intermediate degrees have disappeared from view. Transformation begins when more than one position becomes possible.", prompt: "Which two poles are you treating as the only alternatives? What dimension do they share?" },
    { name: "Rhythm", phrase: "Movements leave traces, intervals and recurrences.", text: "The manuscript uses the wave and the pendulum: rise, fall, advance and retreat. Its value is not in promising that every fall will be compensated exactly, but in teaching us to observe sequences. Conversations, states and projects have different timings. Recognizing rhythm prevents us from confusing one phase with the whole and lets us prepare: save during expansion, rest after effort, or intervene before a repetition closes over itself again.", prompt: "What sequence repeats? Where in the cycle are you today?" },
    { name: "Cause and effect", phrase: "Every action participates in a network of consequences, but rarely acts alone.", text: "The source material speaks of sowing and harvesting. We preserve responsibility without turning it into guilt or punitive karma. One consequence may have many causes, conditions and participants; one action may produce different effects depending on the system it enters. The useful question is not ‘what did I do to deserve this?’ but ‘what actions, omissions and conditions produce or preserve this configuration?’. Where participation becomes visible, response-ability may appear.", prompt: "What sustains this situation today? Separate what depends on you from what does not." },
    { name: "Generation", phrase: "When two forces enter a relationship, a third may emerge that neither contained alone.", text: "The generation documents sought to integrate complementary energies. MPA moves the focus from fixed identities to emergent function. A battery, conductor and lamp do not separately contain the light turned on; the function appears when the relationship configures a circuit. Likewise, two people do not merely affect each other: they may produce a conversation, alliance, rivalry or institution. That third then begins to influence those who generated it.", prompt: "What system does the relationship you are observing produce? What does it enable and preserve?" },
  ],
} as const;

export default function PrincipiosUniversalesWorkshop() {
  const [lang, setLang] = useState<"es" | "en">("es");
  const [checked, setChecked] = useState(false);
  const [access, setAccess] = useState(false);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [active, setActive] = useState(0);
  const [visited, setVisited] = useState<number[]>([0]);
  const [completed, setCompleted] = useState(false);
  const [situation, setSituation] = useState("");
  const [partA, setPartA] = useState("");
  const [partB, setPartB] = useState("");
  const [third, setThird] = useState("");
  const [movement, setMovement] = useState("");
  const [participant, setParticipant] = useState("");
  const [attended, setAttended] = useState(false);
  const t = COPY[lang];

  useEffect(() => {
    setAccess(window.sessionStorage.getItem("pulsus-principios-access") === "open");
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved) try {
      const s = JSON.parse(saved);
      setActive(s.active || 0); setVisited(s.visited || [0]); setCompleted(Boolean(s.completed));
      setSituation(s.situation || ""); setPartA(s.partA || ""); setPartB(s.partB || ""); setThird(s.third || ""); setMovement(s.movement || "");
      setParticipant(s.participant || ""); setAttended(Boolean(s.attended));
    } catch { /* Un guardado anterior no impide entrar. */ }
    setChecked(true);
  }, []);

  const persist = (next: Record<string, unknown> = {}) => window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ active, visited, completed, situation, partA, partB, third, movement, participant, attended, ...next }));
  const go = (index: number) => { const v = Array.from(new Set([...visited, index])).sort(); setActive(index); setVisited(v); persist({ active: index, visited: v }); };
  const save = (setter: (v: string) => void, field: string, value: string) => { setter(value); persist({ [field]: value }); };
  const unlock = async (e: React.FormEvent) => {
    e.preventDefault();
    const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(code.trim().toUpperCase()));
    const hash = Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
    if (hash === ACCESS_HASH) { window.sessionStorage.setItem("pulsus-principios-access", "open"); setAccess(true); setError(""); }
    else setError(t.bad);
  };
  const finish = () => { setCompleted(true); persist({ completed: true }); };
  const printMode = (mode: "workbook" | "certificate") => {
    document.body.dataset.printWorkshop = mode;
    const clean = () => { delete document.body.dataset.printWorkshop; window.removeEventListener("afterprint", clean); };
    window.addEventListener("afterprint", clean); window.print();
  };

  if (!checked) return <main className="school-access-gate" />;
  if (!access) return <main className="school-access-gate"><div className="school-visitor-stars" /><Link className="school-access-back" href="/mpa/transmuta/pulsus-fractum?entry=mpa">← {t.back}</Link><section><div className="school-access-seal"><i>PF</i></div><p>{t.gateOver}</p><h1>{t.gateTitle}</h1><span>{t.gateBody}</span><form onSubmit={unlock}><label htmlFor="pu-access">{t.key}</label><div><input id="pu-access" type="password" value={code} onChange={(e) => { setCode(e.target.value); setError(""); }} autoFocus /><button>{t.open}</button></div><small className={error ? "is-error" : ""}>{error || t.hint}</small></form><button className="pu-lang" onClick={() => setLang(lang === "es" ? "en" : "es")}>{lang === "es" ? "EN" : "ES"}</button></section></main>;

  return <main className="pf-classroom pu-workshop">
    <div className="pf-classroom-stars" />
    <header className="pf-classroom-header"><Link href="/mpa/transmuta/pulsus-fractum?entry=mpa">← {t.back}</Link><span>{t.school}</span><div><button className="pu-lang" onClick={() => setLang(lang === "es" ? "en" : "es")}>{lang === "es" ? "EN" : "ES"}</button><b>{completed ? t.done : t.saved}</b></div></header>
    <div className="pf-classroom-layout">
      <aside className="pf-classroom-index"><p>{t.degree}</p><h2>{t.title}</h2><div className="pf-classroom-progress"><i style={{width: `${completed ? 100 : Math.max(12, visited.length / 7 * 100)}%`}} /></div><small>{completed ? "100%" : `${visited.length} / 7`}</small><nav>{t.sections.map((s, i) => <button key={s} className={active === i ? "is-active" : ""} onClick={() => go(i)}><em>{String(i + 1).padStart(2, "0")}</em><span>{s}</span>{visited.includes(i) ? <b>✓</b> : null}</button>)}</nav><div className="pf-classroom-resource"><span>{t.live}</span><b>{t.pending}</b><a aria-disabled="true">Zoom / Google Meet · pendiente</a></div><div className="pf-classroom-resource"><span>{t.workbook}</span><b>{t.workbookText}</b><a href={lang === "es" ? "/materiales/cuaderno-principios-universales-es.pdf" : "/materiales/cuaderno-principios-universales-en.pdf"} download>{lang === "es" ? "Descargar cuaderno PDF ↓" : "Download workbook PDF ↓"}</a><button onClick={() => printMode("workbook")}>{lang === "es" ? "Imprimir con mis respuestas" : "Print with my answers"}</button></div><div className="pu-campus-benefits"><span>{lang === "es" ? "Tu acceso hoy" : "Your access today"}</span><b>{lang === "es" ? "Ya estás viviendo el campus" : "You are already experiencing the campus"}</b><ul><li>{lang === "es" ? "Aula y recorrido personal" : "Classroom and personal journey"}</li><li>{lang === "es" ? "Progreso y bitácora guardados" : "Saved progress and notebook"}</li><li>{lang === "es" ? "Cuaderno imprimible" : "Printable workbook"}</li><li>{lang === "es" ? "Certificado de participación" : "Participation certificate"}</li></ul><small>{lang === "es" ? "Al iniciar un camino se abren clases, laboratorios, encuentros y biblioteca." : "Joining a pathway opens classes, laboratories, encounters and the library."}</small></div></aside>
      <section className="pf-classroom-content"><div className="pf-classroom-eyebrow">{t.eyebrow}</div><h1>{t.hero}</h1><blockquote>{t.sub}</blockquote><div className="pu-facts"><span>{t.duration}</span><span>{t.mode}</span><span>{t.seven}</span></div>
        <div className="pf-classroom-panel">
          {active === 0 && (lang === "es" ? <article><p className="pf-lesson-label">Antes del encuentro · 5 minutos</p><h2>Prepará una realidad que hoy te esté ocupando.</h2><p>No hace falta que sea extraordinaria. Elegí una conversación, una decisión, un vínculo o una situación que parezca tener una sola explicación.</p><div className="pf-lesson-callout"><b>No venimos a creer siete leyes.</b><span>Vamos a probar siete lentes de observación y verificar qué permiten distinguir.</span></div><label>La situación que traigo</label><textarea value={situation} onChange={(e) => save(setSituation, "situation", e.target.value)} placeholder="Hoy parece evidente que…" /></article> : <article><p className="pf-lesson-label">Before the session · 5 minutes</p><h2>Bring one reality that is occupying you today.</h2><p>Choose a conversation, decision, relationship or situation that seems to have only one explanation.</p><div className="pf-lesson-callout"><b>We are not here to believe seven laws.</b><span>We will test seven lenses and observe what each one allows us to distinguish.</span></div><label>The situation I bring</label><textarea value={situation} onChange={(e) => save(setSituation, "situation", e.target.value)} placeholder="Today it seems evident that…" /></article>)}
          {active === 1 && (lang === "es" ? <article><p className="pf-lesson-label">Umbral · minutos 0–8</p><h2>¿Creamos la realidad o participamos en las configuraciones que la vuelven posible?</h2><p>“Crear tu realidad” no significa controlar todo lo que sucede. Significa reconocer que observamos, elegimos y actuamos dentro de relaciones que también nos configuran.</p><div className="pf-lesson-callout"><b>Regla del taller</b><span>Cada afirmación se trata como una hipótesis para explorar, no como una verdad que debas adoptar.</span></div></article> : <article><p className="pf-lesson-label">Threshold · minutes 0–8</p><h2>Do we create reality, or take part in the configurations that make it possible?</h2><p>“Creating your reality” does not mean controlling everything. It means recognizing how we observe, choose and act within relationships that also configure us.</p><div className="pf-lesson-callout"><b>Workshop rule</b><span>Every statement is a hypothesis to explore, not a truth you must adopt.</span></div></article>)}
          {active === 2 && <article><p className="pf-lesson-label">{lang === "es" ? "Biblioteca de las siete lentes" : "Library of the seven lenses"}</p><h2>{lang === "es" ? "Leé, abrí y probá cada principio" : "Read, open and test each principle"}</h2><p>{lang === "es" ? "No hace falta memorizar. Cada lente contiene una lectura completa, una precisión MPA y una pregunta para llevar a tu propia experiencia." : "You do not need to memorize. Each lens contains a complete reading, an MPA clarification and a question to bring into your own experience."}</p><div className="pu-readings">{READINGS[lang].map((reading, index) => <details key={reading.name} open={index === 0}><summary><em>{String(index + 1).padStart(2, "0")}</em><span><b>{reading.name}</b><small>{reading.phrase}</small></span><i>＋</i></summary><div><p>{reading.text}</p><blockquote>{reading.prompt}</blockquote></div></details>)}</div></article>}
          {active === 3 && (lang === "es" ? <article><p className="pf-lesson-label">Imagen · minutos 18–28</p><h2>Hacer hablar sin explicar demasiado pronto.</h2><p>Durante el encuentro vas a recibir una imagen sin explicación previa. Tu tarea no es adivinar qué significa: es observar cómo tu mirada completa lo que la imagen no dice.</p><ol><li>Nombrá tres datos visibles.</li><li>Marcá una interpretación que apareció sola.</li><li>Escuchá otra lectura sin corregirla.</li><li>¿Qué cambió: la imagen o la configuración desde la que la mirabas?</li></ol></article> : <article><p className="pf-lesson-label">Image · minutes 18–28</p><h2>Make the image speak without explaining too soon.</h2><p>During the live session you will receive an image with no previous explanation. Your task is not to guess what it means, but to observe how your gaze completes what the image does not say.</p><ol><li>Name three visible facts.</li><li>Mark one interpretation that appeared on its own.</li><li>Listen to another reading without correcting it.</li><li>What changed: the image or the configuration from which you viewed it?</li></ol></article>)}
          {active === 4 && (lang === "es" ? <article><p className="pf-lesson-label">Laboratorio · minutos 28–38</p><h2>La relación produce una función que ninguna parte contiene sola.</h2><p>Vas a ver cómo piezas que por separado no iluminan nada producen una función cuando entran en relación. Mirá el circuito y registrá dónde creías que estaba la capacidad de encender.</p><div className="pf-lesson-callout"><b>No tenés que traer materiales</b><span>La experiencia sucede en vivo. En tu cuaderno solo vas a registrar qué cambió en tu manera de mirar la relación.</span></div><div className="pf-lesson-callout"><b>Pregunta</b><span>¿Dónde estaba la luz antes de cerrar el circuito: en una pieza o en la relación?</span></div></article> : <article><p className="pf-lesson-label">Laboratory · minutes 28–38</p><h2>A relationship produces a function that no part contains alone.</h2><p>You will see how pieces that cannot illuminate anything on their own produce a function when they enter into relationship. Observe the circuit and notice where you believed the capacity to light was located.</p><div className="pf-lesson-callout"><b>You do not need to bring materials</b><span>The experience happens live. In your workbook you will only record what changed in the way you observed the relationship.</span></div><div className="pf-lesson-callout"><b>Question</b><span>Where was the light before the circuit closed: in one part, or in the relationship?</span></div></article>)}
          {active === 5 && <article><p className="pf-lesson-label">{lang === "es" ? "Experiencia central · minutos 38–52" : "Core experience · minutes 38–52"}</p><h2>{lang === "es" ? "El tercero que no estabas mirando" : "The third you were not looking at"}</h2><p>{lang === "es" ? "Tomá la situación inicial y separá las dos fuerzas que estabas tratando como únicas. Después observá qué sistema producen juntas." : "Return to your initial situation and separate the two forces you were treating as the only ones. Then observe the system they produce together."}</p><div className="pf-lab-fields"><label>{lang === "es" ? "Primera fuerza" : "First force"}<textarea value={partA} onChange={(e) => save(setPartA, "partA", e.target.value)} /></label><label>{lang === "es" ? "Segunda fuerza" : "Second force"}<textarea value={partB} onChange={(e) => save(setPartB, "partB", e.target.value)} /></label><label className="wide">{lang === "es" ? "El tercero que emerge" : "The third that emerges"}<textarea value={third} onChange={(e) => save(setThird, "third", e.target.value)} placeholder={lang === "es" ? "La relación está produciendo…" : "The relationship is producing…"} /></label></div></article>}
          {active === 6 && <article><p className="pf-lesson-label">{lang === "es" ? "Integración · minutos 52–60" : "Integration · minutes 52–60"}</p><h2>{lang === "es" ? "No salgas con una respuesta. Salí con una observación más precisa." : "Do not leave with an answer. Leave with a more precise observation."}</h2><label>{lang === "es" ? "Un movimiento posible" : "One possible movement"}</label><textarea value={movement} onChange={(e) => save(setMovement, "movement", e.target.value)} placeholder={lang === "es" ? "Después de mirar la configuración, puedo…" : "After observing the configuration, I can…"} /><div className="pf-correspondences"><p>{lang === "es" ? "Lo que te llevás" : "What you take with you"}</p><div><span><b>7</b>{lang === "es" ? "lentes" : "lenses"}</span><span><b>1</b>{lang === "es" ? "situación explorada" : "explored situation"}</span><span><b>1</b>{lang === "es" ? "cuaderno" : "notebook"}</span><span><b>1</b>{lang === "es" ? "continuidad posible" : "possible continuation"}</span></div></div><button className="pu-complete" onClick={finish}>{completed ? t.reopen : t.complete}</button><div className="pu-certificate-form"><h3>{t.certificate}</h3><p>{t.lockedCert}</p><label>{t.name}<input value={participant} onChange={(e) => save(setParticipant, "participant", e.target.value)} /></label><label className="pu-check"><input type="checkbox" checked={attended} onChange={(e) => { setAttended(e.target.checked); persist({ attended: e.target.checked }); }} /> {t.attended}</label><button disabled={!completed || !attended || !participant.trim()} onClick={() => printMode("certificate")}>{t.issue}</button></div></article>}
        </div>
        <div className="pf-classroom-controls"><button disabled={active === 0} onClick={() => go(active - 1)}>{t.previous}</button>{active < 6 && <button className="primary" onClick={() => go(active + 1)}>{t.next}</button>}</div>
      </section>
    </div>
    <section className="pu-print-workbook"><h1>{t.eyebrow}</h1><h2>{t.hero}</h2><p>{t.sub}</p><h3>{lang === "es" ? "Mi situación" : "My situation"}</h3><p>{situation || "________________________________________________________________"}</p><h2 className="pu-print-section-title">{lang === "es" ? "Las siete lentes" : "The seven lenses"}</h2>{READINGS[lang].map((reading, index) => <article key={reading.name}><h3>{index + 1}. {reading.name}</h3><strong>{reading.phrase}</strong><p>{reading.text}</p><blockquote>{reading.prompt}</blockquote><p className="pu-writing-lines">________________________________________________________________<br />________________________________________________________________</p></article>)}<h2 className="pu-print-section-title">{lang === "es" ? "El tercero que no estabas mirando" : "The third you were not looking at"}</h2><h3>{lang === "es" ? "Las dos fuerzas" : "The two forces"}</h3><p>A. {partA || "________________________________________"}</p><p>B. {partB || "________________________________________"}</p><h3>{lang === "es" ? "El tercero que emerge" : "The third that emerges"}</h3><p>{third || "________________________________________________________________"}</p><h3>{lang === "es" ? "Un movimiento posible" : "One possible movement"}</h3><p>{movement || "________________________________________________________________"}</p><footer>Pulsus Fractum · MPA</footer></section>
    <section className="pu-print-certificate"><p>MPA · Escuela de Metalkimia Pulsus Fractum</p><h1>{t.certificate}</h1><span>{lang === "es" ? "Se deja constancia de que" : "This certifies that"}</span><h2>{participant}</h2><span>{lang === "es" ? "participó del taller" : "participated in the workshop"}</span><h3>{t.eyebrow}<br />{t.hero}</h3><footer>{new Date().toLocaleDateString(lang === "es" ? "es-AR" : "en-US")} · MPA</footer></section>
  </main>;
}
